### ISSUE TITLE
License mismatch on inspec 

### ISSUE THREAD

**Issue by Paladin** [chef/homebrew-chef#115]
# Version:

Current

# Environment:

MacOS

# Scenario:

Trying to install chef/inspec from this cask. The first time I try to run inspec, it demands I agree to a completely different license than the one shown here. This one says apache, the one the software is demanding doesn't even exist in front of me. It gives a reference that says of you work for a company, you have to ask permission to use it.

Either change the license you're showing here or change the license you're asking folks to agree to. (inspec itself currently claims to be apache, so that's probably the one to switch it to.) As it current sits the software contradicts itself.

# Steps to Reproduce:

brew cask install chef/inspec
now run inspec

# Expected Result:

I expect either to be prompted to agree to the apache license, or more likely just run.

# Actual Result:

Get a prompt that says I have to agree to the license at a url that says if you work for a company you have to contact chef. (https://www.chef.io/end-user-license-agreement/)

This is definitely *not* the apache license.

**Comment by Paladin** [comment]
And of course there's a typo.

    brew cask install chef/chef/inspec

Sigh.

**Comment by clintoncwolfe** [comment]
Being addressed on https://github.com/inspec/inspec/pull/5073

**Comment by tas50** [comment]
This has been fixed in the inspec packages
