### ISSUE TITLE
Inspec cask doesn't work for Big Sur

### ISSUE THREAD

**Issue by duncaan** [chef/homebrew-chef#153]
# Version:
latest

# Environment:

MacOS 11.1

# Scenario:

Attempting to update inspec through homebrew.

# Steps to Reproduce:

`brew upgrade`

# Expected Result:

Homebrew should download the correct inspec artifact and install it.

# Actual Result:

```
==> Upgrading inspec
==> Downloading https://packages.chef.io/files/stable/inspec/4.24.8/mac_os_x/11/

curl: (22) The requested URL returned error: 404
==> Purging files for version 4.24.8 of Cask inspec
Error: chef/chef/inspec: Download failed on Cask 'inspec' with message: Download failed: https://packages.chef.io/files/stable/inspec/4.24.8/mac_os_x/11/inspec-4.24.8-1.dmg
```

The correct download link is: `https://packages.chef.io/files/stable/inspec/4.24.8/mac_os_x/11.0/inspec-4.24.8-1.dmg`

**Comment by akaspin** [comment]
Any news?

**Comment by tas50** [comment]
Can you try this again now that https://github.com/chef/homebrew-chef/pull/158 is merged

**Comment by duncaan** [comment]
works for me, thanks.
