### ISSUE TITLE
Upgrading Homebrew cask fails because it's looking for a `.dmg` with the wrong name

### ISSUE THREAD

**Issue by davidfetter** [chef/homebrew-chef#174]
# Version:

16.10.8

# Environment:

MacOS Catalina 10.15.7
# Scenario:

Upgrade via homebrew

# Steps to Reproduce:

brew upgrade chef-infra-client

# Expected Result:

Upgraded installation

# Actual Result:

Fails to install because it's looking for a `.dmg` with the wrong name.

It's looking for
`https://packages.chef.io/files/stable/chef/16.10.17/mac_os_x/10.14/chef-16.10.17-1.dmg`
but the name of the new .dmg is
`https://packages.chef.io/files/stable/chef/16.10.17/mac_os_x/10.14/chef-16.10.17-1.x86_64.dmg` <-- I guess this is in anticipation of supporting `M1` or other chipsets.

**Comment by tas50** [comment]
This one should be fixed now
