### ISSUE TITLE
Current ChefDK stable release is 3.5.13, but in cask still 3.4.38

### ISSUE THREAD

**Issue by Nklya** [chef/homebrew-chef#18]
Hello.

I've found a strange thing. Current ChefDK stable release is 3.5.13, but in cask still 3.4.38 

https://downloads.chef.io/chefdk/stable
https://github.com/chef/homebrew-chef/blob/master/Casks/chefdk.rb

**Comment by tas50** [comment]
It looks like our automation to bump the versions didn't fire. I've updated the version by hand. Thanks for letting us know.

**Comment by Nklya** [comment]
Thank you!
