### ISSUE TITLE
EL Capitan should be deprecated in casks

### ISSUE THREAD

**Issue by Nklya** [chef/homebrew-chef#20]
Hello.

I've found that all products that can be installed from this tap are no longer support EL Capitan.
So I think it would be better to change depends_on in chefDK and workstation casks and add the same to inspec cask.
https://github.com/chef/homebrew-chef/blob/master/Casks/chefdk.rb#L11

**Comment by tas50** [comment]
I updated the files to sierra. Thanks for pointing this out.

**Comment by Nklya** [comment]
Thanks!
