### ISSUE TITLE
Chef-workstation download URL does not exist

### ISSUE THREAD

**Issue by ikari7789** [chef/homebrew-chef#241]
The new URL for chef-workstation does not point to a file that exists.

https://github.com/chef/homebrew-chef/blob/6537b395bc2a42a4081cdab1c71f9f7921714782/Casks/chef-workstation.rb#L5

Seems to be the same situation for chef-intra-client too.

https://github.com/chef/homebrew-chef/blob/6537b395bc2a42a4081cdab1c71f9f7921714782/Casks/chef-infra-client.rb#L6

**Comment by tas50** [comment]
Fixed now. Thanks for the report
