### ISSUE TITLE
It would be nice to add cask for chefdk 3.x

### ISSUE THREAD

**Issue by Nklya** [chef/homebrew-chef#36]
### Describe the Enhancement:
Hello. I think it would be nice to add cask for chefdk 3.x.
Like for example it was done in main repo for `terraform@0.11`

### Describe the Need:
Since 4.x includes chef v15 with the new license and it's impossible to use it for non-personal purposes.

### Current Alternative
Install manually from https://downloads.chef.io/chefdk/stable/3.11.3

### Can We Help You Implement This?:
Yes, if you agree that this feature is ok, I can create PR with changes.

**Comment by tas50** [comment]
I'd be open to a PR for that if someone wants it

**Comment by tas50** [comment]
I'm going to close this out at this point since we no longer support DK3 and no one stepped up to open a PR during the support window
